// =========================================================================
// data.js — DocuMed · Diccionarios Predictivos
// Expone globalmente: CIE10_DB, FARMACOS_DB, HOSPITALES_DB
// =========================================================================

const CIE10_DB = [
  "A09 Gastroenteritis y colitis de origen no especificado",
  "A41.9 Sepsis, no especificada",
  "E11.10 Diabetes mellitus tipo 2 con cetoacidosis",
  "E11.65 Diabetes mellitus tipo 2 con hiperglucemia",
  "E16.2 Hipoglucemia no especificada",
  "E86.0 Deshidratación",
  "F10.92 Intoxicación por alcohol, no especificada",
  "F19.2 Trastorno por consumo de múltiples drogas e intoxicación",
  "F41.0 Trastorno de pánico (Ataque de ansiedad)",
  "F41.9 Trastorno de ansiedad, no especificado",
  "G40.909 Epilepsia / Crisis convulsiva, no especificada",
  "G43.9 Migraña, no especificada",
  "G44.89 Otros síndromes de dolor de cabeza (Cefalea)",
  "G45.9 Accidente isquémico transitorio, sin especificar (AIT)",
  "I10 Hipertensión esencial (primaria)",
  "I16.9 Crisis hipertensiva, no especificada",
  "I20.0 Angina inestable",
  "I21.9 Infarto agudo de miocardio, sin especificar (IAM)",
  "I26.9 Embolia pulmonar sin mención de cor pulmonale agudo (TEP)",
  "I46.9 Paro cardíaco, no especificado (PCR)",
  "I48.9 Fibrilación y aleteo auricular, no especificado (FA)",
  "I49.9 Arritmia cardíaca, no especificada",
  "I50.9 Insuficiencia cardíaca, no especificada",
  "I61.9 Hemorragia intracerebral, no especificada",
  "I63.9 Infarto cerebral, no especificado (ICTUS)",
  "I71.9 Aneurisma y disección aórtica, no especificada",
  "J06.9 Infección aguda de vías respiratorias superiores",
  "J18.9 Neumonía, microorganismo no especificado",
  "J44.1 Enfermedad pulmonar obstructiva crónica con exacerbación (EPOC)",
  "J45.9 Asma, no especificada",
  "J81.0 Edema pulmonar agudo",
  "J96.00 Insuficiencia respiratoria aguda, no especificada",
  "K35.80 Apendicitis aguda",
  "K80.20 Cálculo de la vesícula biliar sin colecistitis (Cólico biliar)",
  "K85.9 Pancreatitis aguda, no especificada",
  "K92.2 Hemorragia gastrointestinal, no especificada (HDA/HDB)",
  "M54.2 Cervicalgia",
  "M54.5 Dolor lumbar (Lumbago)",
  "N23 Cólico nefrítico no especificado",
  "N39.0 Infección de vías urinarias, sitio no especificado (ITU)",
  "N93.9 Sangrado vaginal o uterino anormal",
  "O14.9 Preeclampsia, no especificada",
  "O15.9 Eclampsia, no especificada",
  "O20.0 Amenaza de aborto",
  "O80 Parto único espontáneo (Parto inminente / en curso)",
  "O90.81 Hemorragia posparto",
  "R04.0 Epistaxis (Hemorragia nasal)",
  "R06.02 Dificultad para respirar (Disnea)",
  "R06.4 Hiperventilación",
  "R07.4 Dolor en el pecho, no especificado",
  "R10.4 Dolor abdominal, no especificado",
  "R11.2 Náuseas y vómitos",
  "R33.9 Retención de orina, no especificada",
  "R40.20 Coma, no especificado",
  "R41.0 Desorientación, no especificada",
  "R41.82 Alteración del estado mental, no especificada",
  "R42 Mareo y desvanecimiento (Vértigo)",
  "R45.1 Inquietud y agitación psicomotriz",
  "R45.851 Ideación o intento suicida",
  "R50.9 Fiebre, no especificada",
  "R53.83 Fatiga / Astenia",
  "R55 Síncope y colapso",
  "R57.1 Shock hipovolémico",
  "R57.9 Shock, no especificado",
  "S00.9 Traumatismo superficial de la cabeza",
  "S01.9 Herida abierta de la cabeza",
  "S06.0X0A Conmoción cerebral",
  "S06.9X0A Traumatismo craneoencefálico, no especificado (TCE)",
  "S13.4 Esguince y torcedura de la columna cervical (Latigazo cervical)",
  "S22.3 Fractura de costilla",
  "S32.89 Fractura de pelvis",
  "S42.30 Fractura de húmero / hombro",
  "S52.9 Fractura de antebrazo (cúbito / radio)",
  "S62.8 Fractura de muñeca / mano",
  "S72.0 Fractura del cuello de fémur (Fractura de cadera)",
  "S82.9 Fractura de pierna (tibia / peroné)",
  "S92.9 Fractura de pie / tobillo",
  "S93.4 Esguince y torcedura de tobillo",
  "T07 Traumatismos múltiples no especificados (Politraumatismo)",
  "T14.1 Herida abierta, región corporal no especificada",
  "T14.90 Lesión traumática, no especificada",
  "T17.9 Cuerpo extraño en las vías respiratorias (OVACE)",
  "T20-T32 Quemaduras y corrosiones",
  "T40.2X1 Intoxicación por opioides",
  "T42.4X1 Intoxicación por benzodiazepinas",
  "T58 Intoxicación por monóxido de carbono (CO)",
  "T67.0 Golpe de calor y solepsia",
  "T68 Hipotermia",
  "T71.1 Asfixia (Ahorcamiento, estrangulamiento)",
  "T75.1 Ahogamiento y sumersión no mortal",
  "T78.2 Shock anafiláctico, no especificado",
  "Z04.1 Examen y observación después de accidente de transporte",
  "Z04.3 Examen y observación después de presunta violación o abuso",
];

const FARMACOS_DB = [
  "Acenocumarol (Sintrom)",
  "Ácido Acetilsalicílico (AAS)",
  "Ácido Tranexámico (Amchafibrin)",
  "Adenosina",
  "Adrenalina (Epinefrina)",
  "Amiodarona",
  "Amlodipino",
  "Amoxicilina",
  "Amoxicilina / Clavulánico",
  "Atropina",
  "Bicarbonato Sódico 1M",
  "Bicarbonato Sódico 1/6M",
  "Bromuro de Ipratropio",
  "Budesonida",
  "Buprenorfina",
  "Butilescopolamina (Buscapina)",
  "Captopril",
  "Carbón Activado",
  "Ceftriaxona",
  "Ciprofloxacino",
  "Clonazepam",
  "Clopidogrel",
  "Clorpromazina",
  "Cloruro Cálcico",
  "Dexametasona",
  "Dexketoprofeno",
  "Diazepam",
  "Diclofenaco",
  "Digoxina",
  "Dobutamina",
  "Dopamina",
  "Enalapril",
  "Enoxaparina (Clexane)",
  "Etomidato",
  "Fenitoína",
  "Fentanilo",
  "Flumazenilo",
  "Furosemida",
  "Glucagón",
  "Gluconato Cálcico",
  "Haloperidol",
  "Heparina Sódica",
  "Hidrocortisona",
  "Hidroxocobalamina (Antídoto Cianuro)",
  "Ibuprofeno",
  "Insulina Rápida (Actrapid)",
  "Isoprenalina",
  "Ketamina",
  "Ketorolaco",
  "Labetalol",
  "Levetiracetam",
  "Lidocaína",
  "Lorazepam",
  "Metamizol (Nolotil)",
  "Metformina",
  "Metilprednisolona (Urbason)",
  "Metoclopramida (Primperan)",
  "Midazolam",
  "Morfina",
  "Naloxona",
  "Nitroglicerina (Cafinitrina / Solinitrina)",
  "Noradrenalina",
  "Olanzapina",
  "Omeprazol",
  "Ondansetrón",
  "Pantoprazol",
  "Paracetamol",
  "Penicilina",
  "Piridoxina (Vitamina B6)",
  "Prasugrel",
  "Propofol",
  "Rocuronio",
  "Salbutamol",
  "Succinilcolina (Anectine)",
  "Suero Fisiológico 0.9%",
  "Suero Glucosado 5%",
  "Suero Glucosado 10%",
  "Suero Glucosado 50%",
  "Suero Ringer Lactato",
  "Sulfato de Magnesio",
  "Tiamina (Vitamina B1)",
  "Ticagrelor",
  "Tiopental",
  "Tramadol",
  "Urapidilo",
  "Valproato Sódico (Depakine)",
  "Vecuronio",
];

const HOSPITALES_DB = {
  "A Coruña": [
    "C. H. U. de A Coruña (CHUAC)",
    "C. H. U. de Santiago (CHUS)",
    "C. H. U. de Ferrol (CHUF)",
    "Hospital Quirónsalud A Coruña",
    "HM Modelo",
    "Hospital San Rafael",
    "HM Rosaleda",
  ],
  Álava: [
    "H. U. de Álava (Txagorritxu)",
    "H. U. de Álava (Santiago)",
    "Hospital Vithas Vitoria",
    "Clínica IMQ Zorrotzaurre",
  ],
  Albacete: [
    "Complejo H. U. de Albacete (CHUA)",
    "Hospital de Hellín",
    "Hospital General de Almansa",
    "Hospital General de Villarrobledo",
    "Hospital Quirónsalud Albacete",
  ],
  Alicante: [
    "H. G. U. de Alicante",
    "H. G. U. de Elche",
    "H. U. San Juan de Alicante",
    "H. U. del Vinalopó",
    "H. U. de Torrevieja",
    "Hospital de Dénia",
    "Hospital IMED Elche",
    "Hospital IMED Levante",
    "Hospital Vithas Alicante",
    "Hospital Quirónsalud Torrevieja",
    "Hospital HLA Vistahermosa",
  ],
  Almería: [
    "H. U. Torrecárdenas",
    "H. U. Poniente (El Ejido)",
    "Hospital La Inmaculada (Huércal-Overa)",
    "Hospital de Alta Resolución El Toyo",
    "Hospital Vithas Almería",
    "Hospital HLA Mediterráneo",
  ],
  Asturias: [
    "H. U. Central de Asturias (HUCA)",
    "Hospital de Cabueñes",
    "Hospital San Agustín",
    "Hospital Valle del Nalón",
    "Hospital de Jove",
    "Cruz Roja Gijón",
    "Centro Médico de Asturias",
  ],
  Ávila: ["Complejo Asistencial de Ávila"],
  Badajoz: [
    "Complejo H. U. de Badajoz",
    "Hospital de Mérida",
    "Hospital Don Benito-Villanueva",
    "Hospital Quirónsalud Clideba",
    "Hospital Parque Vegas Altas",
  ],
  Baleares: [
    "H. U. Son Espases",
    "H. U. Son Llàtzer",
    "Hospital Mateu Orfila",
    "Hospital Can Misses",
    "Hospital Quirónsalud Palmaplanas",
    "Clínica Rotger",
    "Red Asistencial Juaneda",
  ],
  Barcelona: [
    "Hospital Clínic",
    "H. U. Vall d'Hebron",
    "H. U. de Bellvitge",
    "Hospital de la Santa Creu i Sant Pau",
    "H. del Mar",
    "H. U. Germans Trias i Pujol (Can Ruti)",
    "Parc Taulí",
    "Mutua Terrassa",
    "Hospital Quirónsalud Barcelona",
    "Centro Médico Teknon",
    "Hospital Universitari Dexeus",
    "HM Delfos",
    "Hospital Sagrat Cor",
  ],
  Burgos: [
    "H. U. de Burgos (HUBU)",
    "Hospital Santiago Apóstol",
    "Hospital Santos Reyes",
    "Hospital Recoletas Burgos",
  ],
  Cáceres: [
    "Complejo H. U. de Cáceres",
    "Hospital Virgen del Puerto (Plasencia)",
    "Hospital Quirónsalud Cáceres",
  ],
  Cádiz: [
    "H. U. Puerta del Mar",
    "H. U. de Jerez",
    "H. U. de Puerto Real",
    "Hospital Punta de Europa (Algeciras)",
    "Hospital de La Línea",
    "Hospital San Carlos (San Fernando)",
    "Hospital de Alta Resolución La Janda",
    "Hospital Viamed Bahía de Cádiz",
    "Hospital HLA La Salud",
    "Hospital Quirónsalud Campo de Gibraltar",
  ],
  Cantabria: [
    "H. U. Marqués de Valdecilla",
    "Hospital Comarcal de Laredo",
    "Hospital Sierrallana",
    "Hospital Mompía",
    "Mutua Montañesa",
  ],
  Castellón: [
    "H. G. U. de Castellón",
    "Hospital de la Plana",
    "Hospital Comarcal de Vinaròs",
    "Hospital Vithas Castellón",
  ],
  Ceuta: ["H. U. de Ceuta"],
  "Ciudad Real": [
    "H. G. U. de Ciudad Real",
    "Hospital Mancha Centro (Alcázar)",
    "Hospital de Puertollano",
    "Hospital de Tomelloso",
    "Hospital Quirónsalud Ciudad Real",
  ],
  Córdoba: [
    "H. U. Reina Sofía",
    "Hospital Infanta Margarita (Cabra)",
    "Hospital Valle de los Pedroches (Pozoblanco)",
    "Hospital de Alta Resolución de Montilla",
    "Hospital de Alta Resolución de Puente Genil",
    "Hospital de Alta Resolución Valle del Guadiato",
    "Hospital Quirónsalud Córdoba",
    "Hospital Cruz Roja Córdoba",
    "Hospital San Juan de Dios",
  ],
  Cuenca: ["Hospital Virgen de la Luz", "Hospital Recoletas Cuenca"],
  Girona: [
    "H. U. Dr. Josep Trueta",
    "Hospital de Santa Caterina",
    "Hospital de Figueres",
    "Hospital de Palamós",
    "Clínica Girona",
  ],
  Granada: [
    "H. U. Virgen de las Nieves",
    "H. U. Clínico San Cecilio (PTS)",
    "Hospital Santa Ana (Motril)",
    "Hospital de Baza",
    "Hospital de Alta Resolución de Guadix",
    "Hospital de Alta Resolución de Loja",
    "Hospital Vithas Granada",
    "Hospital HLA Inmaculada",
  ],
  Guadalajara: ["H. U. de Guadalajara", "Clínica La Antigua"],
  Gipuzkoa: [
    "H. U. Donostia",
    "Hospital Bidasoa",
    "Hospital Quirónsalud Donostia",
    "Policlínica Gipuzkoa",
  ],
  Huelva: [
    "H. U. Juan Ramón Jiménez",
    "Hospital Infanta Elena",
    "Hospital de Riotinto",
    "Hospital Quirónsalud Huelva",
  ],
  Huesca: [
    "Hospital San Jorge",
    "Hospital de Barbastro",
    "Hospital Viamed Santiago",
  ],
  Jaén: [
    "H. U. de Jaén",
    "Hospital San Agustín (Linares)",
    "Hospital San Juan de la Cruz (Úbeda)",
    "Hospital Alto Guadalquivir (Andújar)",
    "Hospital de Alta Resolución de Alcaudete",
    "Hospital de Alta Resolución Sierra de Segura",
    "Hospital de Alta Resolución Alcalá la Real",
    "Hospital Cristo Rey",
  ],
  "La Rioja": [
    "Hospital San Pedro",
    "Fundación Hospital de Calahorra",
    "Hospital Viamed Los Manzanos",
  ],
  "Las Palmas": [
    "H. U. de Gran Canaria Dr. Negrín",
    "Complejo H. U. Insular",
    "H. G. de Fuerteventura",
    "H. G. Dr. José Molina Orosa (Lanzarote)",
    "Hospitales San Roque",
    "Hospital Vithas Las Palmas",
    "Hospiten Roca",
  ],
  León: [
    "Complejo Asistencial Universitario de León",
    "Hospital del Bierzo",
    "Hospital San Juan de Dios León",
    "Hospital Regla",
  ],
  Lleida: [
    "H. U. Arnau de Vilanova",
    "Hospital Santa Maria",
    "Hospital Vithas Lleida",
  ],
  Lugo: [
    "H. U. Lucus Augusti (HULA)",
    "Hospital da Mariña",
    "Hospital de Monforte",
    "Hospital Polusa",
  ],
  Madrid: [
    "H. U. La Paz",
    "H. U. 12 de Octubre",
    "H. G. U. Gregorio Marañón",
    "H. U. Ramón y Cajal",
    "H. Clínico San Carlos",
    "H. U. Puerta de Hierro",
    "H. U. La Princesa",
    "H. U. Niño Jesús",
    "H. U. Fundación Jiménez Díaz",
    "HM Sanchinarro",
    "HM Montepríncipe",
    "HM Puerta del Sur",
    "Hospital Quirónsalud Madrid",
    "Ruber Internacional",
    "Hospital Sanitas La Zarzuela",
    "Hospital Sanitas La Moraleja",
    "Hospital Vithas Madrid Arturo Soria",
  ],
  Málaga: [
    "H. Regional U. de Málaga (Carlos Haya)",
    "H. U. Virgen de la Victoria (Clínico)",
    "Hospital Costa del Sol (Marbella)",
    "Hospital de la Axarquía (Vélez-Málaga)",
    "Hospital de la Serranía (Ronda)",
    "Hospital de Antequera",
    "Hospital de Alta Resolución de Benalmádena",
    "Hospital de Alta Resolución Valle del Guadalhorce",
    "Hospital Quirónsalud Málaga",
    "Hospital Quirónsalud Marbella",
    "Hospital Vithas Málaga",
    "HM Málaga",
  ],
  Melilla: ["Hospital Comarcal de Melilla"],
  Murcia: [
    "H. Clínico U. Virgen de la Arrixaca",
    "H. G. U. Morales Meseguer",
    "H. G. U. Reina Sofía",
    "H. G. U. Santa Lucía",
    "Hospital Los Arcos del Mar Menor",
    "Hospital Quirónsalud Murcia",
    "Hospital HLA La Vega",
    "Hospital Mesa del Castillo",
  ],
  Navarra: [
    "Hospital Universitario de Navarra (HUN)",
    "Hospital García Orcoyen",
    "Hospital Reina Sofía",
    "Clínica Universidad de Navarra (CUN)",
    "Hospital San Juan de Dios Pamplona",
  ],
  Ourense: [
    "Complejo H. U. de Ourense (CHUO)",
    "Hospital de Verín",
    "Hospital de Valdeorras",
    "Centro Médico El Carmen",
    "Hospital Cosaga",
  ],
  Palencia: [
    "Complejo Asistencial de Palencia (Río Carrión)",
    "Hospital Recoletas Palencia",
  ],
  Pontevedra: [
    "Complejo H. U. de Vigo (Álvaro Cunqueiro)",
    "Complejo H. U. de Pontevedra (CHOP)",
    "Hospital Povisa",
    "Hospital Vithas Vigo",
    "Hospital Quirónsalud Miguel Domínguez",
  ],
  Salamanca: [
    "Complejo Asistencial Universitario de Salamanca",
    "Hospital General de la Santísima Trinidad",
  ],
  Segovia: ["Complejo Asistencial de Segovia", "Hospital Recoletas Segovia"],
  Sevilla: [
    "H. U. Virgen del Rocío",
    "H. U. Virgen Macarena",
    "H. U. Virgen de Valme",
    "Hospital San Juan de Dios del Aljarafe (Bormujos)",
    "Hospital de la Merced (Osuna)",
    "Hospital de Alta Resolución de Utrera",
    "Hospital de Alta Resolución de Écija",
    "Hospital de Alta Resolución de Lebrija",
    "Hospital de Alta Resolución Sierra Norte (Constantina)",
    "Hospital Quirónsalud Sagrado Corazón",
    "Hospital Quirónsalud Infanta Luisa",
    "Hospital Vithas Sevilla",
    "Hospital HLA Santa Isabel",
  ],
  Soria: ["Complejo Asistencial de Soria (Santa Bárbara)"],
  Tarragona: [
    "H. U. Joan XXIII",
    "Hospital Sant Joan de Reus",
    "Hospital Verge de la Cinta",
    "Hospital Viamed Monegal",
  ],
  "Santa Cruz de Tenerife": [
    "H. U. N. S. de Candelaria",
    "H. U. de Canarias (HUC)",
    "H. G. de La Palma",
    "H. Ntra. Sra. de Guadalupe",
    "H. Ntra. Sra. de los Reyes",
    "Hospiten Sur",
    "Hospital Quirónsalud Tenerife",
    "Hospital San Juan de Dios Tenerife",
  ],
  Teruel: [
    "Hospital Obispo Polanco",
    "Hospital de Alcañiz",
    "Hospital San José",
  ],
  Toledo: [
    "H. U. de Toledo",
    "Hospital N. S. del Prado (Talavera)",
    "Hospital Quirónsalud Toledo",
    "Hospital Quirónsalud Tres Culturas",
  ],
  Valencia: [
    "H. U. i Politècnic La Fe",
    "H. Clínico U. de Valencia",
    "H. G. U. de Valencia",
    "H. U. Dr. Peset",
    "H. Arnau de Vilanova",
    "H. U. de la Ribera",
    "H. de Manises",
    "Hospital Quirónsalud Valencia",
    "Hospital Vithas Valencia 9 de Octubre",
    "Hospital IMED Valencia",
    "Hospital Casa de Salud",
  ],
  Valladolid: [
    "H. Clínico U. de Valladolid",
    "H. U. Río Hortega",
    "Hospital de Medina del Campo",
    "Hospital Recoletas Campo Grande",
    "Hospital Sagrado Corazón",
  ],
  Zamora: [
    "Complejo Asistencial de Zamora (Virgen de la Concha)",
    "Hospital Recoletas Zamora",
  ],
  Zaragoza: [
    "H. U. Miguel Servet",
    "H. Clínico U. Lozano Blesa",
    "Hospital Royo Villanova",
    "Hospital Quirónsalud Zaragoza",
    "Hospital Viamed Montecanal",
    "Hospital MAZ",
  ],
};
